const taskArrangement = [
    {
        date:'2021-7-15',
        info:[
            {
                position:'广东特别牛逼战队 一区',
                task:[
                    {
                        start:'00:00',
                        end:"01:30",
                        place:"腾讯视频"
                    },
                    {
                        start:'05:00',
                        end:"05:30",
                        place:"爱奇艺"
                    },
                ]
            },
            {
                position:'广东特别牛逼战队 二区',
                task:[
                    {
                        start:'00:00',
                        end:"01:30",
                        place:"腾讯视频"
                    },
                    {
                        start:'05:00',
                        end:"05:30",
                        place:"爱奇艺"
                    },
                ]
            },
        ]
    },
    {
        date:'2021-8-15',
        info:[
            {
                position:'广东特水牛战队 一区',
                task:[
                    {
                        start:'00:00',
                        end:"01:30",
                        place:"腾讯视频"
                    },
                    {
                        start:'05:00',
                        end:"05:30",
                        place:"爱奇艺"
                    },
                ]
            },
            {
                position:'广东水牛战队 二区',
                task:[
                    {
                        start:'00:00',
                        end:"01:30",
                        place:"腾讯视频"
                    },
                    {
                        start:'05:00',
                        end:"05:30",
                        place:"爱奇艺"
                    },
                ]
            },
        ]
    },
    {
        date:'2021-10-15',
        info:[
            {
                position:'广东特区 一区',
                task:[
                    {
                        start:'00:00',
                        end:"01:30",
                        place:"腾讯视频"
                    },
                    {
                        start:'05:00',
                        end:"05:30",
                        place:"爱奇艺"
                    },
                ]
            }
        ]
    },
    {
        date:'2021-10-16',
        info:[
            {
                position:'广东特别 一区',
                task:[
                    {
                        start:'00:00',
                        end:"01:30",
                        place:"腾讯视频"
                    },
                    {
                        start:'05:00',
                        end:"05:30",
                        place:"爱奇艺"
                    },
                ]
            }
        ]
    },
]
export{
    taskArrangement
}